id = "phpstan"
name = "PHPStan"
description = "PHPStan static analysis integration for Zed"
version = "0.1.0"
schema_version = 1
authors = ["Peter"]

[language_servers.phpstan]
name = "PHPStan"
languages = ["PHP"]
